SELECT SALDO_A_VENCER_30_DIAS
FROM WILTON_GALVAO.SC_CART_TBF_REC_CENT_RIS_MCLCL CL
WHERE CL.CPF LIKE '27114913826'
AND REGEXP_LIKE(SALDO_A_VENCER_30_DIAS,'[a-zA-Z!"#$%&()*,.:;?@^_`´\/-{\|}~+<=>¨\/\[]');


SELECT LENGTH(TO_NUMBER(SALDO_OP_ATIVAS)) AS TM ,
  SUM(SALDO_OP_ATIVAS),
  COUNT(*)
FROM WILTON_GALVAO.SC_CART_TBF_REC_CENT_RIS_MCLCL
WHERE SALDO_OP_ATIVAS IS NOT NULL
GROUP BY LENGTH(TO_NUMBER(SALDO_OP_ATIVAS));