-- Desabilita todos os indices 
  EXECUTE IMMEDIATE 'ALTER INDEX  SC_DW_TS_FATURAMENTO_IDX01 UNUSABLE';
  EXECUTE IMMEDIATE 'ALTER INDEX  SC_DW_TS_FATURAMENTO_IDX02 UNUSABLE';
  EXECUTE IMMEDIATE 'ALTER INDEX  SC_DW_TS_FATURAMENTO_IDX03 UNUSABLE';
  EXECUTE IMMEDIATE 'ALTER INDEX  SC_DW_TS_FATURAMENTO_IDX04 UNUSABLE';
  EXECUTE IMMEDIATE 'ALTER INDEX  SC_DW_TS_FATURAMENTO_IDX05 UNUSABLE';
  EXECUTE IMMEDIATE 'ALTER INDEX  SC_DW_TS_FATURAMENTO_IDX06 UNUSABLE';
  EXECUTE IMMEDIATE 'ALTER INDEX  SC_DW_TS_FATURAMENTO_IDX07 UNUSABLE';
  EXECUTE IMMEDIATE 'ALTER INDEX  SC_DW_TS_FATURAMENTO_IDX08 UNUSABLE';
  EXECUTE IMMEDIATE 'ALTER SESSION SET SKIP_UNUSABLE_INDEXES = TRUE' ; 


 -- Manutenção dos indices  
EXECUTE IMMEDIATE 'ALTER INDEX  SC_DW_TS_FATURAMENTO_IDX01 REBUILD PARTITION P_'||VISAO||' COMPUTE STATISTICS' ;
EXECUTE IMMEDIATE 'ALTER INDEX  SC_DW_TS_FATURAMENTO_IDX02 REBUILD PARTITION P_'||VISAO||' COMPUTE STATISTICS' ;
EXECUTE IMMEDIATE 'ALTER INDEX  SC_DW_TS_FATURAMENTO_IDX03 REBUILD PARTITION P_'||VISAO||' COMPUTE STATISTICS' ;
EXECUTE IMMEDIATE 'ALTER INDEX  SC_DW_TS_FATURAMENTO_IDX04 REBUILD PARTITION P_'||VISAO||' COMPUTE STATISTICS' ;
EXECUTE IMMEDIATE 'ALTER INDEX  SC_DW_TS_FATURAMENTO_IDX05 REBUILD PARTITION P_'||VISAO||' COMPUTE STATISTICS' ;
EXECUTE IMMEDIATE 'ALTER INDEX  SC_DW_TS_FATURAMENTO_IDX06 REBUILD PARTITION P_'||VISAO||' COMPUTE STATISTICS' ;
EXECUTE IMMEDIATE 'ALTER INDEX  SC_DW_TS_FATURAMENTO_IDX07 REBUILD PARTITION P_'||VISAO||' COMPUTE STATISTICS' ;
EXECUTE IMMEDIATE 'ALTER INDEX  SC_DW_TS_FATURAMENTO_IDX08 REBUILD PARTITION P_'||VISAO||' COMPUTE STATISTICS' ;


-- skip_unusable_indexes = true
-- cria index particionado sem construi-lo
create index PL_CLIENTE_IDX_BT02 on PL_CLIENTE_CALC (COD_DP_PL) local unusable; 


-- reconstroi o indice 
alter index PL_CLIENTE_IDX_BT02 rebuild partition p_201607 ;



To make all local indexes on a partition unusable:
ALTER TABLE ANDRE_SANTOS.SC_DW_TS_FATURAMENTO_ MODIFY PARTITION p_201510 UNUSABLE LOCAL INDEXES;

To rebuild:
ALTER TABLE ANDRE_SANTOS.SC_DW_TS_FATURAMENTO_ MODIFY PARTITION p_201510 REBUILD UNUSABLE LOCAL INDEXES COMPUTE STATISTICS;


